name: Check CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ 'main', 'release/v*' ]

jobs:
  check:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        customDoubleParser: [ 'fast-double-parser', 'none' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Check gitignore rules
        run: .github/scripts/check-gitignore-rules.sh

      - name: Setup JDKs
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: |
            8
            11
            17
            21
            25

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Setup gradle properties
        run: |
          cat .github/env/${{ runner.os }}/gradle.properties >> gradle.properties
          echo >> gradle.properties
          echo "org.gradle.java.installations.paths=$JAVA_HOME_8_X64,$JAVA_HOME_11_X64,$JAVA_HOME_17_X64,$JAVA_HOME_21_X64,$JAVA_HOME_25_X64" >> gradle.properties
          echo "customDoubleParser=${{ matrix.customDoubleParser }}" >> gradle.properties
          cat gradle.properties

      - name: Check
        run: ./gradlew check

      - name: Upload Artifacts
        uses: actions/upload-artifact@v6
        if: always()
        with:
          name: check-artifacts-${{ matrix.customDoubleParser }}
          path: |
            **/build/reports/tests/**
            **/build/test-results/**
            !**/build/test-results/**/binary/**
            **/*_pid*.log
